// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef CANBURGLER_H
#define CANBURGLER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class CanBurgler: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DoubleSolenoid* RightCanBurglerSolenoid;
	DoubleSolenoid* LeftCanBurglerSolenoid;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	CanBurgler();
	void InitDefaultCommand();
    void ExtendRight();
    void ExtendLeft();
    void ExtendBoth();
    void RetractRight();
    void RetractLeft();
    void RetractBoth();
    bool IsRightExtended();
    bool IsLeftExtended();
};

#endif
