// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
#ifndef CONFIG_H
#define CONFIG_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

class Config: public Subsystem {
private:
public:
	Config();
	~Config();
	void InitDefaultCommand();
	void ReadConfig();
	void SetConfig();
	void SaveConfiguration();
	std::string RobotName;
	bool LED_Enable;
	int  LED_AlianceIndicator;
	int  LED_AlianceBlue;
	int  LED_AutoIndicator;
	int  LED_TeleopIndicator;
};

#endif
