// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "Config.h"
#include "../RobotMap.h"
#include "../Robot.h"
#include "../OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

Config::Config() : Subsystem("Config") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

Config::~Config()
{

}

void Config::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

void Config::ReadConfig(){
	RobotName = Preferences::GetInstance()->GetString("RobotType");
	LED_Enable = Preferences::GetInstance()->GetBoolean("LED::Enable",false);
	LED_AlianceIndicator = Preferences::GetInstance()->GetInt("LED::AlianceIndicator",-1);
	LED_AlianceBlue = Preferences::GetInstance()->GetInt("LED::AlianceBlue",1);
	LED_AutoIndicator = Preferences::GetInstance()->GetInt("LED::AutoIndicator",-1);
	LED_TeleopIndicator = Preferences::GetInstance()->GetInt("LED::TeleopIndicator",-1);
	Robot::forwardDrive->RetrieveConfig();
	Robot::strafingDrive->RetrieveConfig();
	Robot::elevatorLift->RetrieveConfig();
	Robot::liftGrabber->RetrieveConfig();
	Robot::spinners->RetrieveConfig();
	Robot::brake->RetrieveConfig();
	Robot::canBurgler->RetrieveConfig();
	Robot::pneumatics->RetrieveConfig();
	Robot::oi->getDriverInterface()->RetrieveConfig();
	Robot::oi->getOperatorInterface()->RetrieveConfig();
	Robot::autonomousConfig->RetrieveConfig();
}


void Config::SetConfig(){
	Preferences::GetInstance()->PutString("RobotType",RobotName.c_str());
	Preferences::GetInstance()->PutBoolean("LED::Enable",LED_Enable);
	Preferences::GetInstance()->PutInt("LED::AlianceIndicator",LED_AlianceIndicator);
	Preferences::GetInstance()->PutInt("LED::AlianceBlue",LED_AlianceBlue);
	Preferences::GetInstance()->PutInt("LED::AutoIndicator",LED_AutoIndicator);
	Preferences::GetInstance()->PutInt("LED::TeleopIndicator",LED_TeleopIndicator);
	Robot::forwardDrive->StoreConfig();
	Robot::strafingDrive->StoreConfig();
	Robot::elevatorLift->StoreConfig();
	Robot::liftGrabber->StoreConfig();
	Robot::spinners->StoreConfig();
	Robot::brake->StoreConfig();
	Robot::canBurgler->StoreConfig();
	Robot::pneumatics->StoreConfig();
	Robot::oi->getDriverInterface()->StoreConfig();
	Robot::autonomousConfig->StoreConfig();
}

void Config::SaveConfiguration(){
	Preferences::GetInstance()->Save();
}

