// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ELEVATORLIFT_H
#define ELEVATORLIFT_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../Configurable.h"

class ElevatorLift_Config;

class ElevatorLift: public Subsystem, public Configurable {
private:
	ElevatorLift_Config *myConfig;
	float pulsesPerInch;
	double travel;
	float tote,clearance;
	float rate;
	bool beenHome;
	double cmdHeight;
	bool positioning;
	int posErr;
	double ZeroPoint;

public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	CANTalon* liftTalon;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	ElevatorLift();
	virtual ~ElevatorLift();
	virtual void RetrieveConfig();
	virtual void StoreConfig();
	virtual void Configure();

	void InitDefaultCommand();
	void Set_LiftHome();                         // Moves lift to bottom (Home) position and sets encoder to 0.
	void Home();                                 // Move lift to home position. Only works if Set_LiftHome has been called.
	void MoveLift(float val);                    // This moves the lift at a specific rate.
	void MoveLiftToPosition(double pos);         // This moves the lift to a specific number of inches from the home position.
	void MoveLiftToRelativePosition(double pos); // This moves the lift a specific number of inches from the current position.
	void StopLift();
	double Get_Position();
	bool AtCommandedPosition();
	bool AtBottom();
	bool AtTop();
	void Set_PositionMode();
	void Set_VoltageMode();
	void Set_PosZero();  // This sets current position to zero. Will only set to 0 if at bottom.
};

#endif
