// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef ELEVATORLIFT_H
#define ELEVATORLIFT_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class ElevatorLift: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	void SetLiftConfig();
	float pulsesPerInch;
	double travel;
	float tote,clearance;
	float rate;

public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	CANTalon* liftTalon;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	ElevatorLift();
	void InitDefaultCommand();
	void Set_LiftHome();
	void Home();
	double Get_Position();
	double Up_OneTote();
	double Down_OneTote();
	void RaiseLift();
	void LowerLift();
	void MoveLift(float val);
	void StopLift();
	bool AtBottom();
	bool AtTop();
};

#endif
