// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef IMU_SENSOR_H
#define IMU_SENSOR_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "IMU/AHRS.h"
#include "IMU_Sensor_Config.h"
#include "../Configurable.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class IMU_Sensor: public Subsystem, public Configurable {
private:
	IMU_Sensor_Config *myConfig;
	NetworkTable *table;
	AHRS *imu;
	SerialPort *serial_port;
	bool first_iteration;

public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	IMU_Sensor();
	virtual ~IMU_Sensor();

	virtual void RetrieveConfig();
	virtual void StoreConfig();
	virtual void Configure();

	void InitDefaultCommand();

	bool IsCalibrating();
	void UpdateSmartDash();


};

#endif
