// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef LIFTGRABBER_H
#define LIFTGRABBER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../Configurable.h"

class LiftGrabber_Config;

class LiftGrabber: public Subsystem, public Configurable {
private:
	LiftGrabber_Config *myConfig;
	bool opened;
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Solenoid* liftGrabberSolenoid;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	LiftGrabber();
	virtual ~LiftGrabber();
	virtual void RetrieveConfig();
	virtual void StoreConfig();
	virtual void Configure();

	void InitDefaultCommand();

	void Open();
	void Close();
	void Toggle();
	bool Is_Open();
};

#endif
