// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef STRAFINGDRIVE_H
#define STRAFINGDRIVE_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "Configurable.h"

class StrafingDrive_Config;

class StrafingDrive: public Subsystem, public Configurable {
private:
	StrafingDrive_Config *myConfig;

	float   PulsesPerInch;
	float HighSpeedRate;
	float LowSpeedRate;
	CANTalon* Master;
	CANTalon* Slave;
	bool positioning;
	int lPosErr;
	int rPosErr;
	int posErr;
	double distance;
	double ZeroPoint;


public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	CANTalon* strafeRightTalon;
	CANTalon* strafeLeftTalon;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	StrafingDrive();
	virtual ~StrafingDrive();
	virtual void RetrieveConfig();
	virtual void StoreConfig();
	virtual void Configure();


	void InitDefaultCommand();
	void SetDrive_Arcade(float x, bool highRate = false);
	void LinearDrive(float inches);
	void SetManualDistance(float inches);
    bool AtCommandedPosition();


	void Stop();
	void Set_PositionMode();
	void Set_VoltageMode();
	void Zero_Encoder();
	int Get_Encoder();
	float Limit(float num);

};

#endif
