// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef STRAFINGDRIVE_H
#define STRAFINGDRIVE_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class StrafingDrive: public Subsystem {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	int   PulsesPerInch;
	float HighSpeedRate;
	float LowSpeedRate;
	CANTalon* Master;
	CANTalon* Slave;

public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	CANTalon* strafeRightTalon;
	CANTalon* strafeLeftTalon;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	StrafingDrive();
	void InitDefaultCommand();
	void SetDrive_Arcade(float x, bool highRate = false);
	void LinearDrive(float inches);

	void Stop();
	void Set_PositionMode();
	void Set_SpeedMode();
	void Zero_Encoder();
	int Get_Encoder();
	void Config();
	float Limit(float num);

};

#endif
