// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutoJerk.h"

AutoJerk::AutoJerk(float distance) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

	MaxFDThrottle = Robot::autonomousConfig->Autonomous_MaxFDThrottle;
	ThrottleRamp = Robot::autonomousConfig->Autonomous_ThrottleRamp;
	dist = distance;
	Throttle = 0.0;
	first = false;
}

// Called just before this Command runs the first time
void AutoJerk::Initialize() {
//	Robot::strafingDrive->Set_VoltageMode();
	Robot::forwardDrive->Set_VoltageMode();
	first = false;
}

// Called repeatedly when this Command is scheduled to run
void AutoJerk::Execute() {
	if (first == false)
	{
		first = true;
		printf("AJ exe setting zero points. \n");
//		Robot::strafingDrive->Zero_Encoder();
//		Robot::strafingDrive->SetManualDistance(dist);
		Robot::forwardDrive->Zero_Encoders();
		Robot::forwardDrive->SetManualDistance(dist);
		Throttle = 0.0;
	}
	if (dist < 0)
	{
		if (Throttle > (-1 * MaxFDThrottle) )
		{
			Throttle -= ThrottleRamp;
		}
	} else
	{
		if (Throttle < MaxFDThrottle )
		{
			Throttle += ThrottleRamp;
		}
	}

	//Robot::strafingDrive->SetDrive_Arcade(Throttle,true);
	Robot::forwardDrive->SetDrive_Arcade(0,Throttle,true);
}

// Make this return true when this Command no longer needs to run execute()
bool AutoJerk::IsFinished() {
//	return Robot::strafingDrive->AtCommandedPosition();
	return Robot::forwardDrive->AtCommandedPosition();
}

// Called once after isFinished returns true
void AutoJerk::End() {
//	Robot::strafingDrive->Stop();
	Robot::forwardDrive->Stop();
	Throttle = 0.0;
	first = false;
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutoJerk::Interrupted() {

}
