// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "MoveStrafeDrive.h"

MoveStrafeDrive::MoveStrafeDrive() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// Requires(Robot::strafingDrive);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::strafingDrive);
}

// Called just before this Command runs the first time
void MoveStrafeDrive::Initialize() {
	
}

// Called repeatedly when this Command is scheduled to run
void MoveStrafeDrive::Execute() {
	axisState = Robot::oi->getDriverInterface()->Get_AxisState();
	if (axisState.RTrigger > 0.0)
	{
		Robot::strafingDrive->SetDrive_Arcade(axisState.Raw_RX, true);
	} else
	{
		Robot::strafingDrive->SetDrive_Arcade(axisState.Raw_RX, false);
	}
}

// Make this return true when this Command no longer needs to run execute()
bool MoveStrafeDrive::IsFinished() {
		return false;
}

// Called once after isFinished returns true
void MoveStrafeDrive::End() {
	Robot::strafingDrive->Stop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void MoveStrafeDrive::Interrupted() {

}
