// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "MoveElevatorLift.h"

MoveElevatorLift::MoveElevatorLift() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// Requires(Robot::elevatorLift);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::elevatorLift);
}

// Called just before this Command runs the first time
void MoveElevatorLift::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void MoveElevatorLift::Execute() {
	axisState = Robot::oi->getOperatorInterface()->Get_AxisState();
	if ((axisState.Raw_LY) != 0.0)
	{
		Robot::brake->Release();
	    Robot::elevatorLift->MoveLift(axisState.Raw_LY);
	} else
	{
		Robot::elevatorLift->StopLift();
		Robot::brake->Engage();
	}
}

// Make this return true when this Command no longer needs to run execute()
bool MoveElevatorLift::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void MoveElevatorLift::End() {
	Robot::elevatorLift->StopLift();
	Robot::brake->Engage();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void MoveElevatorLift::Interrupted() {

}
