// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Select_Auto_CanGrab.h"

Select_Auto_CanGrab::Select_Auto_CanGrab() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void Select_Auto_CanGrab::Initialize() {
	Robot::robotInstance->Select_CanGrab_Auto();
}

// Called repeatedly when this Command is scheduled to run
void Select_Auto_CanGrab::Execute() {
	
}

// Make this return true when this Command no longer needs to run execute()
bool Select_Auto_CanGrab::IsFinished() {
	return true;
}

// Called once after isFinished returns true
void Select_Auto_CanGrab::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Select_Auto_CanGrab::Interrupted() {

}
