// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutoCanGrab.h"
//#include "Commands/AutoGrabTote.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/CloseLiftGrabber.h"
#include "Commands/EngageBrake.h"
//#include "Commands/LiftDownOneTote.h"
#include "Commands/LiftHome.h"
//#include "Commands/LiftUpOneTote.h"
#include "Commands/MoveElevatorLift.h"
#include "Commands/MoveForwardDrive.h"
#include "Commands/MoveFwdDriveByVector.h"
#include "Commands/MoveStrafeDrive.h"
#include "Commands/OpenLiftGrabber.h"
#include "Commands/ReleaseBrake.h"
#include "Commands/RotateByDegree.h"
#include "Commands/SetLiftHome.h"
#include "Commands/SpinnersIn.h"
#include "Commands/SpinnersOut.h"
#include "Commands/SpinnersRotateClk.h"
//#include "Commands/StrafeByDistMag.h"
#include "Commands/ExtendCanBurgler.h"
#include "Commands/RetractCanBurgler.h"
//#include "Commands/PickupTote.h"
//#include "Commands/PlaceTote.h"
#include "Commands/Select_Auto_None.h"
#include "Commands/Select_Auto_DriveBack.h"
#include "Commands/Select_Auto_CanGrab.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Commands/AutonomousType2.h"
#include "Xbox360_Controller.h"

OI::OI() {
	// Process operator interface input here.

	driverInterface = new XBOX360_Controller("Driver",0);

	operatorInterface = new XBOX360_Controller("Operator",1);
	
    operatorInterface->Assign_ButtonCommand(XBOX360_BUTTON::XBOX360_B, new ExtendCanBurgler(),ButtonAction::ButtonAction_Pressed);

    operatorInterface->Assign_ButtonCommand(XBOX360_BUTTON::XBOX360_B, new RetractCanBurgler(),ButtonAction::ButtonAction_Released);

        // SmartDashboard Buttons
//	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

//	SmartDashboard::PutData("SpinnersIn", new SpinnersIn());

//	SmartDashboard::PutData("SpinnersOut", new SpinnersOut());

//	SmartDashboard::PutData("SpinnersRotateClk", new SpinnersRotateClk());

	SmartDashboard::PutData("OpenLiftGrabber", new OpenLiftGrabber());

	SmartDashboard::PutData("CloseLiftGrabber", new CloseLiftGrabber());

	SmartDashboard::PutData("EngageBrake", new EngageBrake());

	SmartDashboard::PutData("ReleaseBrake", new ReleaseBrake());

	SmartDashboard::PutData("SetLiftHome", new SetLiftHome());

	SmartDashboard::PutData("Select_Auto_None", new Select_Auto_None());

	SmartDashboard::PutData("Select_Auto_DriveBack", new Select_Auto_DriveBack());

	SmartDashboard::PutData("Select_Auto_CanGrab", new Select_Auto_CanGrab());

//	SmartDashboard::PutData("LiftUpOneTote", new LiftUpOneTote());

//	SmartDashboard::PutData("LiftHome", new LiftHome());

//	SmartDashboard::PutData("MoveStrafeDrive", new MoveStrafeDrive());

//	SmartDashboard::PutData("MoveForwardDrive", new MoveForwardDrive());

//	SmartDashboard::PutData("RotateByDegree", new RotateByDegree(90.0));

//	SmartDashboard::PutData("AutoCanGrab", new AutoCanGrab());

	SmartDashboard::PutData("AutonomousType2", new AutonomousType2());

	SmartDashboard::PutData("AutoCanGrab", new AutoCanGrab());

//	SmartDashboard::PutData("StrafeByDistMag", new StrafeByDistMag());

//	SmartDashboard::PutData("MoveFwdDriveByVector", new MoveFwdDriveByVector());

//	SmartDashboard::PutData("LiftDownOneTote", new LiftDownOneTote());

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}



XBOX360_Controller* OI::getOperatorInterface() {
	return operatorInterface;
}

XBOX360_Controller* OI::getDriverInterface() {
	return driverInterface;
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
