// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AddToStack.h"
#include "Commands/AutoCanGrab.h"
#include "Commands/AutoGoBack.h"
#include "Commands/AutoGoFwd.h"
#include "Commands/AutoGrabTote.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/CloseLiftGrabber.h"
#include "Commands/EngageBrake.h"
#include "Commands/LiftDownOneTote.h"
#include "Commands/LiftHome.h"
#include "Commands/LiftUpOneTote.h"
#include "Commands/MoveLift.h"
#include "Commands/MoveForwardDrive.h"
#include "Commands/MoveFwdDriveByVector.h"
#include "Commands/MoveStrafeDrive.h"
#include "Commands/OpenLiftGrabber.h"
#include "Commands/ReleaseBrake.h"
#include "Commands/RotateByDegree.h"
#include "Commands/SetLiftHome.h"
#include "Commands/SpinnersIn.h"
#include "Commands/SpinnersOut.h"
#include "Commands/SpinnersRotateClk.h"
#include "Commands/StrafeByDistMag.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

#include "Xbox360_Controller.h"

OI::OI() {
	// Process operator interface input here.


	//operatorInterface = new Joystick(1);

	//driverInterface = new Joystick(0);
	
	operatorInterface = new XBOX360_Controller("Operator",1);
    operatorInterface->Assign_ButtonCommand(XBOX360_BUTTON::XBOX360_RIGHT_BUMPER,new SpinnersOut());
    operatorInterface->Assign_ButtonCommand(XBOX360_BUTTON::XBOX360_LEFT_BUMPER, new SpinnersIn());
    operatorInterface->Assign_ButtonCommand(XBOX360_BUTTON::XBOX360_RIGHT_STICK, new SpinnersRotateClk());
	


	driverInterface = new XBOX360_Controller("Driver",0);




        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

	SmartDashboard::PutData("SpinnersIn", new SpinnersIn());

	SmartDashboard::PutData("SpinnersOut", new SpinnersOut());

	SmartDashboard::PutData("SpinnersRotateClk", new SpinnersRotateClk());

	SmartDashboard::PutData("OpenLiftGrabber", new OpenLiftGrabber());

	SmartDashboard::PutData("CloseLiftGrabber", new CloseLiftGrabber());

	SmartDashboard::PutData("EngageBrake", new EngageBrake());

	SmartDashboard::PutData("ReleaseBrake", new ReleaseBrake());

	SmartDashboard::PutData("SetLiftHome", new SetLiftHome());

	SmartDashboard::PutData("AddToStack", new AddToStack());

	SmartDashboard::PutData("LiftUpOneTote", new LiftUpOneTote());

	SmartDashboard::PutData("LiftHome", new LiftHome());

	SmartDashboard::PutData("MoveStrafeDrive", new MoveStrafeDrive());

	SmartDashboard::PutData("MoveForwardDrive", new MoveForwardDrive());

	SmartDashboard::PutData("RotateByDegree", new RotateByDegree());

	SmartDashboard::PutData("AutoCanGrab", new AutoCanGrab());

	SmartDashboard::PutData("AutoGoBack", new AutoGoBack());

	SmartDashboard::PutData("AutoGoFwd", new AutoGoFwd());

	SmartDashboard::PutData("AutoGrabTote", new AutoGrabTote());

	SmartDashboard::PutData("StrafeByDistMag", new StrafeByDistMag());

	SmartDashboard::PutData("MoveFwdDriveByVector", new MoveFwdDriveByVector());

	SmartDashboard::PutData("LiftDownOneTote", new LiftDownOneTote());

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}



XBOX360_Controller* OI::getOperatorInterface() {
	return operatorInterface;
}

XBOX360_Controller* OI::getDriverInterface() {
	return driverInterface;
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
